export interface Location {
  street: string
  city: string
  state: string
}

export const locations: Location[] = [
  { street: 'Grasskamp', city: 'Lancaster', state: 'Pennsylvania' },
  { street: 'Darwin', city: 'Valley Forge', state: 'Pennsylvania' },
  { street: 'Dayton', city: 'Glendale', state: 'California' },
  { street: 'Anzinger', city: 'Tuscaloosa', state: 'Alabama' },
  { street: 'Blackbird', city: 'Lubbock', state: 'Texas' },
  { street: 'Golden Leaf', city: 'Salem', state: 'Oregon' },
  { street: 'Longview', city: 'Greeley', state: 'Colorado' },
  { street: 'Elka', city: 'Houston', state: 'Texas' },
  { street: 'Fremont', city: 'Salinas', state: 'California' },
  { street: 'Del Mar', city: 'Austin', state: 'Texas' },
  { street: 'Heffernan', city: 'Naples', state: 'Florida' },
  { street: 'Vidon', city: 'Shreveport', state: 'Louisiana' },
  { street: 'Gale', city: 'Colorado Springs', state: 'Colorado' },
  { street: 'Hanson', city: 'Macon', state: 'Georgia' },
  { street: 'Hermina', city: 'Sacramento', state: 'California' },
  { street: 'Saint Paul', city: 'New York City', state: 'New York' },
  { street: 'Vermont', city: 'Springfield', state: 'Illinois' },
  { street: 'Weeping Birch', city: 'Pueblo', state: 'Colorado' },
  { street: 'Artisan', city: 'Worcester', state: 'Massachusetts' },
  { street: 'Hovde', city: 'Sacramento', state: 'California' },
  { street: 'Crownhardt', city: 'New York City', state: 'New York' },
  { street: 'Dakota', city: 'Minneapolis', state: 'Minnesota' },
  { street: 'Trailsway', city: 'Laredo', state: 'Texas' },
  { street: 'Artisan', city: 'Juneau', state: 'Alaska' },
  { street: 'Florence', city: 'Henderson', state: 'Nevada' },
  { street: 'Northport', city: 'Philadelphia', state: 'Pennsylvania' },
  { street: 'Weeping Birch', city: 'Evansville', state: 'Indiana' },
  { street: 'Daystar', city: 'Winston Salem', state: 'North Carolina' },
  { street: 'Larry', city: 'Miami Beach', state: 'Florida' },
  { street: 'Spohn', city: 'Kansas City', state: 'Kansas' },
  {
    street: 'Westerfield',
    city: 'Washington',
    state: 'District of Columbia',
  },
  { street: 'Farwell', city: 'San Diego', state: 'California' },
  { street: 'La Follette', city: 'Dallas', state: 'Texas' },
  { street: 'Parkside', city: 'Memphis', state: 'Tennessee' },
  { street: 'Mitchell', city: 'Philadelphia', state: 'Pennsylvania' },
  { street: 'Ridge Oak', city: 'Charlotte', state: 'North Carolina' },
  { street: 'Myrtle', city: 'Odessa', state: 'Texas' },
  { street: 'Forest Run', city: 'Valdosta', state: 'Georgia' },
  { street: 'Grover', city: 'Dulles', state: 'Virginia' },
  { street: 'Fulton', city: 'Columbus', state: 'Ohio' },
  { street: 'Mallard', city: 'Charleston', state: 'West Virginia' },
  { street: 'Corben', city: 'Wichita', state: 'Kansas' },
  { street: 'Maple', city: 'Houston', state: 'Texas' },
  { street: 'Center', city: 'Mobile', state: 'Alabama' },
  { street: 'Elgar', city: 'Charlotte', state: 'North Carolina' },
  { street: 'Oriole', city: 'Clearwater', state: 'Florida' },
  { street: 'Melrose', city: 'Saint Louis', state: 'Missouri' },
  { street: 'Independence', city: 'Fort Worth', state: 'Texas' },
  { street: 'Welch', city: 'Syracuse', state: 'New York' },
  { street: 'Badeau', city: 'San Antonio', state: 'Texas' },
  { street: 'Randy', city: 'Corpus Christi', state: 'Texas' },
  { street: 'Roth', city: 'Portland', state: 'Oregon' },
  { street: 'Macpherson', city: 'Asheville', state: 'North Carolina' },
  { street: 'Burrows', city: 'Minneapolis', state: 'Minnesota' },
  { street: 'Stoughton', city: 'Minneapolis', state: 'Minnesota' },
  { street: 'Hazelcrest', city: 'Fresno', state: 'California' },
  { street: 'Bellgrove', city: 'Honolulu', state: 'Hawaii' },
  { street: 'Dakota', city: 'Miami', state: 'Florida' },
  { street: 'Dapin', city: 'Pittsburgh', state: 'Pennsylvania' },
  { street: 'Westport', city: 'Boise', state: 'Idaho' },
  { street: 'Lotheville', city: 'Erie', state: 'Pennsylvania' },
  { street: 'Kings', city: 'Atlanta', state: 'Georgia' },
  { street: 'Miller', city: 'Schenectady', state: 'New York' },
  { street: '8th', city: 'Charleston', state: 'West Virginia' },
  { street: 'Florence', city: 'Houston', state: 'Texas' },
  { street: 'Cascade', city: 'Vancouver', state: 'Washington' },
  { street: 'Stuart', city: 'Roanoke', state: 'Virginia' },
  { street: 'Golden Leaf', city: 'Portland', state: 'Oregon' },
  { street: 'Green', city: 'Trenton', state: 'New Jersey' },
  { street: 'Rutledge', city: 'Dallas', state: 'Texas' },
  { street: 'Westridge', city: 'Dallas', state: 'Texas' },
  { street: 'Glacier Hill', city: 'Lehigh Acres', state: 'Florida' },
  { street: 'East', city: 'Watertown', state: 'Massachusetts' },
  { street: 'Manitowish', city: 'Honolulu', state: 'Hawaii' },
  { street: 'Rusk', city: 'New Orleans', state: 'Louisiana' },
  { street: 'Graceland', city: 'Spring Hill', state: 'Florida' },
  { street: 'Schiller', city: 'Phoenix', state: 'Arizona' },
  { street: 'Vidon', city: 'El Paso', state: 'Texas' },
  { street: 'Marcy', city: 'Los Angeles', state: 'California' },
  { street: 'Commercial', city: 'New Orleans', state: 'Louisiana' },
  { street: 'Clove', city: 'San Francisco', state: 'California' },
  { street: 'Schiller', city: 'Salt Lake City', state: 'Utah' },
  { street: 'Fulton', city: 'Tacoma', state: 'Washington' },
  { street: 'Bunting', city: 'Birmingham', state: 'Alabama' },
  { street: 'Spenser', city: 'Minneapolis', state: 'Minnesota' },
  { street: 'Green Ridge', city: 'Dallas', state: 'Texas' },
  { street: 'Jay', city: 'Fort Pierce', state: 'Florida' },
  { street: 'Kedzie', city: 'Baton Rouge', state: 'Louisiana' },
  { street: 'Pennsylvania', city: 'Terre Haute', state: 'Indiana' },
  { street: 'Fremont', city: 'Salem', state: 'Oregon' },
  { street: 'Linden', city: 'Houston', state: 'Texas' },
  { street: 'Rockefeller', city: 'Hartford', state: 'Connecticut' },
  { street: 'Dovetail', city: 'Bloomington', state: 'Indiana' },
  { street: 'La Follette', city: 'Simi Valley', state: 'California' },
  { street: 'Mandrake', city: 'Bethesda', state: 'Maryland' },
  { street: 'Artisan', city: 'Tulsa', state: 'Oklahoma' },
  { street: 'Towne', city: 'Tucson', state: 'Arizona' },
  { street: 'Burrows', city: 'Milwaukee', state: 'Wisconsin' },
  { street: 'Mitchell', city: 'Fullerton', state: 'California' },
  { street: 'Northview', city: 'Brooklyn', state: 'New York' },
  { street: 'Fremont', city: 'Springfield', state: 'Illinois' },
  {
    street: 'Wayridge',
    city: 'Washington',
    state: 'District of Columbia',
  },
  { street: 'Atwood', city: 'Las Vegas', state: 'Nevada' },
  { street: 'Debra', city: 'Oxnard', state: 'California' },
  { street: 'Blaine', city: 'Saint Louis', state: 'Missouri' },
  { street: 'Prairieview', city: 'Sacramento', state: 'California' },
  { street: 'Anniversary', city: 'Cincinnati', state: 'Ohio' },
  { street: 'Continental', city: 'Rochester', state: 'New York' },
  { street: 'Tennyson', city: 'Abilene', state: 'Texas' },
  { street: 'Columbus', city: 'Norwalk', state: 'Connecticut' },
  { street: 'Heath', city: 'Hartford', state: 'Connecticut' },
  { street: 'Memorial', city: 'Spring Hill', state: 'Florida' },
  { street: 'Randy', city: 'Newton', state: 'Massachusetts' },
  { street: 'Arizona', city: 'San Jose', state: 'California' },
  { street: 'Veith', city: 'El Paso', state: 'Texas' },
  { street: 'Londonderry', city: 'Dallas', state: 'Texas' },
  { street: 'Veith', city: 'Killeen', state: 'Texas' },
  { street: 'Clemons', city: 'Pasadena', state: 'California' },
  { street: 'Bluestem', city: 'Newark', state: 'Delaware' },
  { street: 'Anhalt', city: 'Dayton', state: 'Ohio' },
  { street: 'Westridge', city: 'Louisville', state: 'Kentucky' },
  { street: 'Shasta', city: 'Orange', state: 'California' },
  { street: 'Memorial', city: 'Independence', state: 'Missouri' },
  { street: 'Hauk', city: 'Columbus', state: 'Ohio' },
  { street: 'Evergreen', city: 'Indianapolis', state: 'Indiana' },
  { street: 'Tennyson', city: 'Houston', state: 'Texas' },
  { street: 'Washington', city: 'Albuquerque', state: 'New Mexico' },
  { street: 'Wayridge', city: 'Anchorage', state: 'Alaska' },
  { street: 'Blackbird', city: 'Charlotte', state: 'North Carolina' },
  { street: 'Steensland', city: 'Dallas', state: 'Texas' },
  { street: 'Oxford', city: 'Denton', state: 'Texas' },
  { street: 'Bunting', city: 'El Paso', state: 'Texas' },
  { street: 'Kenwood', city: 'Gainesville', state: 'Florida' },
  { street: 'Eggendart', city: 'Merrifield', state: 'Virginia' },
  { street: 'Gale', city: 'Pittsburgh', state: 'Pennsylvania' },
  { street: 'Dovetail', city: 'Fresno', state: 'California' },
  { street: 'Jana', city: 'Plano', state: 'Texas' },
  { street: 'Utah', city: 'El Paso', state: 'Texas' },
  { street: 'Sloan', city: 'Raleigh', state: 'North Carolina' },
  { street: 'Saint Paul', city: 'Saint Paul', state: 'Minnesota' },
  { street: 'Hagan', city: 'Omaha', state: 'Nebraska' },
  { street: 'Haas', city: 'Chicago', state: 'Illinois' },
  { street: 'Dawn', city: 'Charleston', state: 'West Virginia' },
  { street: 'Butterfield', city: 'Springfield', state: 'Virginia' },
  { street: 'Anthes', city: 'Amarillo', state: 'Texas' },
  { street: 'Pawling', city: 'Saint Louis', state: 'Missouri' },
  { street: 'Corry', city: 'Chicago', state: 'Illinois' },
  { street: 'Clarendon', city: 'Chula Vista', state: 'California' },
  { street: 'Schurz', city: 'Minneapolis', state: 'Minnesota' },
  { street: 'American', city: 'Phoenix', state: 'Arizona' },
  { street: 'Iowa', city: 'Amarillo', state: 'Texas' },
  { street: 'Helena', city: 'Lexington', state: 'Kentucky' },
  { street: 'Butterfield', city: 'Beaverton', state: 'Oregon' },
  { street: 'Drewry', city: 'Des Moines', state: 'Iowa' },
  { street: 'Nancy', city: 'San Diego', state: 'California' },
  { street: 'Hudson', city: 'San Jose', state: 'California' },
  { street: 'Hagan', city: 'Nashville', state: 'Tennessee' },
  { street: 'Kipling', city: 'Atlanta', state: 'Georgia' },
  { street: 'Hoffman', city: 'Apache Junction', state: 'Arizona' },
  { street: 'Schlimgen', city: 'Mc Keesport', state: 'Pennsylvania' },
  { street: 'Valley Edge', city: 'Tampa', state: 'Florida' },
  { street: 'Cottonwood', city: 'Houston', state: 'Texas' },
  { street: 'Moulton', city: 'Akron', state: 'Ohio' },
  { street: '6th', city: 'Sparks', state: 'Nevada' },
  { street: 'Sherman', city: 'Dallas', state: 'Texas' },
  { street: 'Ohio', city: 'Oceanside', state: 'California' },
  { street: '3rd', city: 'Lubbock', state: 'Texas' },
  { street: 'Michigan', city: 'Pittsburgh', state: 'Pennsylvania' },
  { street: 'Paget', city: 'Columbia', state: 'South Carolina' },
  { street: 'Swallow', city: 'Watertown', state: 'Massachusetts' },
  { street: 'Pennsylvania', city: 'Peoria', state: 'Illinois' },
  { street: 'Colorado', city: 'Stockton', state: 'California' },
  { street: 'Menomonie', city: 'Silver Spring', state: 'Maryland' },
  { street: 'Fulton', city: 'Corpus Christi', state: 'Texas' },
  { street: 'Blue Bill Park', city: 'Honolulu', state: 'Hawaii' },
  { street: 'Caliangt', city: 'Saint Louis', state: 'Missouri' },
  { street: 'Express', city: 'Rochester', state: 'New York' },
  { street: 'Golf View', city: 'Topeka', state: 'Kansas' },
  { street: 'Hudson', city: 'Memphis', state: 'Tennessee' },
  { street: 'Kedzie', city: 'Washington', state: 'District of Columbia' },
  { street: 'Ohio', city: 'El Paso', state: 'Texas' },
  { street: 'Shoshone', city: 'Phoenix', state: 'Arizona' },
  { street: 'Hayes', city: 'Macon', state: 'Georgia' },
  { street: 'Michigan', city: 'Brooklyn', state: 'New York' },
  { street: 'Warner', city: 'Bronx', state: 'New York' },
  { street: 'Rockefeller', city: 'Mountain View', state: 'California' },
  { street: 'Hermina', city: 'Des Moines', state: 'Iowa' },
  { street: 'Menomonie', city: 'Dallas', state: 'Texas' },
  { street: 'Algoma', city: 'Rochester', state: 'Minnesota' },
  { street: 'Dryden', city: 'Wichita', state: 'Kansas' },
  { street: 'Oxford', city: 'Indianapolis', state: 'Indiana' },
  { street: 'Debra', city: 'Wichita Falls', state: 'Texas' },
  { street: 'Dovetail', city: 'Cedar Rapids', state: 'Iowa' },
  { street: 'Old Shore', city: 'Murfreesboro', state: 'Tennessee' },
  { street: 'Nelson', city: 'Jackson', state: 'Mississippi' },
  { street: 'Northland', city: 'Pensacola', state: 'Florida' },
  { street: 'Sunfield', city: 'Indianapolis', state: 'Indiana' },
  { street: 'Mitchell', city: 'Oakland', state: 'California' },
  { street: 'Sutteridge', city: 'Saint Paul', state: 'Minnesota' },
  { street: 'Birchwood', city: 'Petaluma', state: 'California' },
  { street: 'Goodland', city: 'Pensacola', state: 'Florida' },
  { street: 'Nancy', city: 'Omaha', state: 'Nebraska' },
  { street: 'Oxford', city: 'Toledo', state: 'Ohio' },
  { street: 'Cambridge', city: 'Rockford', state: 'Illinois' },
  { street: 'Waxwing', city: 'New Orleans', state: 'Louisiana' },
  { street: 'Corry', city: 'Houston', state: 'Texas' },
  { street: 'Annamark', city: 'Decatur', state: 'Georgia' },
  { street: 'Dottie', city: 'Charleston', state: 'West Virginia' },
  { street: 'Westridge', city: 'Sarasota', state: 'Florida' },
  { street: 'Sugar', city: 'Baton Rouge', state: 'Louisiana' },
  { street: 'Magdeline', city: 'Kent', state: 'Washington' },
  { street: 'Jenifer', city: 'Portland', state: 'Oregon' },
  { street: 'Grayhawk', city: 'Sacramento', state: 'California' },
  { street: 'Knutson', city: 'Athens', state: 'Georgia' },
  { street: 'Carey', city: 'Washington', state: 'District of Columbia' },
  { street: 'Briar Crest', city: 'Hagerstown', state: 'Maryland' },
  { street: 'Dovetail', city: 'Oakland', state: 'California' },
  { street: 'Dixon', city: 'Orlando', state: 'Florida' },
  { street: 'Susan', city: 'San Antonio', state: 'Texas' },
  { street: 'Banding', city: 'Yakima', state: 'Washington' },
  { street: 'Reindahl', city: 'Saint Louis', state: 'Missouri' },
  { street: 'Schurz', city: 'Humble', state: 'Texas' },
  { street: 'Northview', city: 'El Paso', state: 'Texas' },
  { street: 'Shasta', city: 'Colorado Springs', state: 'Colorado' },
  { street: 'East', city: 'Anchorage', state: 'Alaska' },
  { street: 'Utah', city: 'Oklahoma City', state: 'Oklahoma' },
  { street: 'Browning', city: 'Baltimore', state: 'Maryland' },
  { street: 'Vahlen', city: 'West Palm Beach', state: 'Florida' },
  { street: 'Donald', city: 'Memphis', state: 'Tennessee' },
  { street: 'Dapin', city: 'Portland', state: 'Oregon' },
  { street: 'Orin', city: 'Nashville', state: 'Tennessee' },
  { street: 'Southridge', city: 'New York City', state: 'New York' },
  { street: 'Parkside', city: 'Houston', state: 'Texas' },
  { street: 'Northridge', city: 'Indianapolis', state: 'Indiana' },
  { street: 'Tomscot', city: 'San Francisco', state: 'California' },
  { street: 'Del Sol', city: 'New York City', state: 'New York' },
  {
    street: 'Kenwood',
    city: 'Washington',
    state: 'District of Columbia',
  },
  { street: 'Dovetail', city: 'Chicago', state: 'Illinois' },
  { street: 'Hoard', city: 'Dayton', state: 'Ohio' },
  { street: 'Arrowood', city: 'Herndon', state: 'Virginia' },
  { street: 'Carberry', city: 'Young America', state: 'Minnesota' },
  { street: 'Morrow', city: 'Sparks', state: 'Nevada' },
  { street: 'Sunfield', city: 'Long Beach', state: 'California' },
  { street: 'Scott', city: 'Bradenton', state: 'Florida' },
  { street: 'Gulseth', city: 'Houston', state: 'Texas' },
  { street: 'Pond', city: 'Lansing', state: 'Michigan' },
  { street: 'Knutson', city: 'New York City', state: 'New York' },
  { street: 'Westerfield', city: 'Nashville', state: 'Tennessee' },
  { street: 'Oriole', city: 'Fort Pierce', state: 'Florida' },
  { street: 'Messerschmidt', city: 'Sioux City', state: 'Iowa' },
]
