const rules: CountryRules = {
  fields: {
    country: {
      label: 'country',
      hidden: true,
      maxLength: 100,
    },
    state: {
      label: 'stateAbbreviation',
      maxLength: 100,
      required: true,
      options: [
        { label: 'AL', value: 'AL' },
        { label: 'AK', value: 'AK' },
        { label: 'AZ', value: 'AZ' },
        { label: 'AR', value: 'AR' },
        { label: 'CA', value: 'CA' },
        { label: 'CO', value: 'CO' },
        { label: 'CT', value: 'CT' },
        { label: 'DE', value: 'DE' },
        { label: 'DC', value: 'DC' },
        { label: 'FL', value: 'FL' },
        { label: 'GA', value: 'GA' },
        { label: 'HI', value: 'HI' },
        { label: 'ID', value: 'ID' },
        { label: 'IL', value: 'IL' },
        { label: 'IN', value: 'IN' },
        { label: 'IA', value: 'IA' },
        { label: 'KS', value: 'KS' },
        { label: 'KY', value: 'KY' },
        { label: 'LA', value: 'LA' },
        { label: 'ME', value: 'ME' },
        { label: 'MD', value: 'MD' },
        { label: 'MA', value: 'MA' },
        { label: 'MI', value: 'MI' },
        { label: 'MN', value: 'MN' },
        { label: 'MS', value: 'MS' },
        { label: 'MO', value: 'MO' },
        { label: 'MT', value: 'MT' },
        { label: 'NE', value: 'NE' },
        { label: 'NV', value: 'NV' },
        { label: 'NH', value: 'NH' },
        { label: 'NJ', value: 'NJ' },
        { label: 'NM', value: 'NM' },
        { label: 'NY', value: 'NY' },
        { label: 'NC', value: 'NC' },
        { label: 'ND', value: 'ND' },
        { label: 'OH', value: 'OH' },
        { label: 'OK', value: 'OK' },
        { label: 'OR', value: 'OR' },
        { label: 'PA', value: 'PA' },
        { label: 'PR', value: 'PR' },
        { label: 'RI', value: 'RI' },
        { label: 'SC', value: 'SC' },
        { label: 'SD', value: 'SD' },
        { label: 'TN', value: 'TN' },
        { label: 'TX', value: 'TX' },
        { label: 'UT', value: 'UT' },
        { label: 'VT', value: 'VT' },
        { label: 'VA', value: 'VA' },
        { label: 'WA', value: 'WA' },
        { label: 'WV', value: 'WV' },
        { label: 'WI', value: 'WI' },
        { label: 'WY', value: 'WY' },
      ],
    },
    city: {
      label: 'city',
      maxLength: 100,
      required: true,
    },
    neighborhood: {
      label: 'neighborhood',
      hidden: true,
      maxLength: 100,
    },
    street: {
      label: 'addressLine1',
      required: true,
    },
    number: {
      label: 'number',
      maxLength: 750,
      hidden: true,
      autoComplete: 'nope',
    },
    complement: {
      label: 'addressLine2',
      maxLength: 750,
    },
    reference: {
      label: 'reference',
      hidden: true,
      maxLength: 750,
    },
    receiverName: {
      label: 'receiverName',
      elementName: 'receiver',
      maxLength: 750,
      required: true,
    },
    postalCode: {
      label: 'postalCode',
      forgottenURL: 'https://tools.usps.com/go/ZipLookupAction_input',
    },
  },
  display: {
    minimal: [[{ name: 'postalCode' }]],
    compact: [
      [{ name: 'street' }],
      [
        { name: 'city' },
        { delimiter: ' ', name: 'state' },
        { delimiter: ' ', name: 'postalCode' },
      ],
    ],
    extended: [
      [{ name: 'receiverName' }],
      [{ name: 'street' }, { delimiter: ' ', name: 'complement' }],
      [
        { name: 'number' },
        { delimiter: ', ', name: 'city' },
        { delimiter: ', ', name: 'neighborhood' },
      ],
      [
        { name: 'city' },
        { delimiter: ' ', name: 'state' },
        { delimiter: ' ', name: 'postalCode' },
      ],
    ],
  },
}

export default rules
