import { CountryRules } from '../typings/countryRulesTypes.d'

const rules: CountryRules = {
  fields: {
    country: {
      label: 'country',
      hidden: true,
      maxLength: 100,
      size: 'medium',
    },
    state: {
      label: 'stateAbbreviation',
      maxLength: 100,
      required: true,
      size: 'large',
      optionsPairs: [
        { label: 'Alabama', value: 'AL' },
        { label: 'Alaska', value: 'AK' },
        { label: 'Arizona', value: 'AZ' },
        { label: 'Arkansas', value: 'AR' },
        { label: 'California', value: 'CA' },
        { label: 'Colorado', value: 'CO' },
        { label: 'Connecticut', value: 'CT' },
        { label: 'Delaware', value: 'DE' },
        { label: 'District Of Columbia (Washington, D.C.)', value: 'DC' },
        { label: 'Florida', value: 'FL' },
        { label: 'Georgia', value: 'GA' },
        { label: 'Hawaii', value: 'HI' },
        { label: 'Idaho', value: 'ID' },
        { label: 'Illinois', value: 'IL' },
        { label: 'Indiana', value: 'IN' },
        { label: 'Iowa', value: 'IA' },
        { label: 'Kansas', value: 'KS' },
        { label: 'Kentucky', value: 'KY' },
        { label: 'Louisiana', value: 'LA' },
        { label: 'Maine', value: 'ME' },
        { label: 'Maryland', value: 'MD' },
        { label: 'Massachusetts', value: 'MA' },
        { label: 'Michigan', value: 'MI' },
        { label: 'Minnesota', value: 'MN' },
        { label: 'Mississippi', value: 'MS' },
        { label: 'Missouri', value: 'MO' },
        { label: 'Montana', value: 'MT' },
        { label: 'Nebraska', value: 'NE' },
        { label: 'Nevada', value: 'NV' },
        { label: 'New Hampshire', value: 'NH' },
        { label: 'New Jersey', value: 'NJ' },
        { label: 'New Mexico', value: 'NM' },
        { label: 'New York', value: 'NY' },
        { label: 'North Carolina', value: 'NC' },
        { label: 'North Dakota', value: 'ND' },
        { label: 'Ohio', value: 'OH' },
        { label: 'Oklahoma', value: 'OK' },
        { label: 'Oregon', value: 'OR' },
        { label: 'Pennsylvania', value: 'PA' },
        { label: 'Puerto Rico', value: 'PR' },
        { label: 'Rhode Island', value: 'RI' },
        { label: 'South Carolina', value: 'SC' },
        { label: 'South Dakota', value: 'SD' },
        { label: 'Tennessee', value: 'TN' },
        { label: 'Texas', value: 'TX' },
        { label: 'Utah', value: 'UT' },
        { label: 'Vermont', value: 'VT' },
        { label: 'Virginia', value: 'VA' },
        { label: 'Washington', value: 'WA' },
        { label: 'West Virginia', value: 'WV' },
        { label: 'Wisconsin', value: 'WI' },
        { label: 'Wyoming', value: 'WY' },
      ],
    },
    city: {
      label: 'city',
      maxLength: 100,
      required: true,
      size: 'large',
    },
    neighborhood: {
      label: 'neighborhood',
      hidden: true,
      maxLength: 100,
      size: 'large',
    },
    street: {
      label: 'addressLine1',
      required: true,
      size: 'xlarge',
    },
    number: {
      label: 'number',
      maxLength: 750,
      hidden: true,
      // defaultValue: 'N/A',
      autoComplete: 'nope',
    },
    complement: {
      label: 'addressLine2',
      maxLength: 750,
      size: 'xlarge',
    },
    reference: {
      label: 'reference',
      hidden: true,
      maxLength: 750,
      size: 'xlarge',
    },
    receiverName: {
      label: 'receiverName',
      elementName: 'receiver',
      maxLength: 750,
      size: 'xlarge',
      required: true,
    },
  },
  display: {
    minimal: [[{ name: 'postalCode' }]],
    compact: [
      [{ name: 'street' }],
      [
        { name: 'city' },
        { delimiter: ' ', name: 'state' },
        { delimiter: ' ', name: 'postalCode' },
      ],
    ],
    extended: [
      [{ name: 'receiverName' }],
      [{ name: 'street' }, { delimiter: ' ', name: 'complement' }],
      [
        { name: 'number' },
        { delimiter: ', ', name: 'city' },
        { delimiter: ', ', name: 'neighborhood' },
      ],
      [
        { name: 'city' },
        { delimiter: ' ', name: 'state' },
        { delimiter: ' ', name: 'postalCode' },
      ],
    ],
  },
}

export default rules
